name: CD
on:
  workflow_run:
    workflows: [CI]
    types:
      - completed

jobs:
  cd-three-tier-deployment:
    name: "Deploy Three Tier Application"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup SSH
        shell: bash
        run: |
          eval `ssh-agent -s`
          mkdir -p /home/runner/.ssh
          touch /home/runner/.ssh/privkey.pem
          echo -e "${{secrets.SSH_KEY}}" > /home/runner/.ssh/privkey.pem
          chmod 400 /home/runner/.ssh/privkey.pem
      - name: Run Ansible playbook
        shell: bash
        run: |
          service ssh status
          sudo apt install ansible --yes
          ansible-playbook -i inventory -l database final-playbook.yml
          ansible-playbook -i inventory -l backend final-playbook.yml
          ansible-playbook -i inventory -l frontend final-playbook.yml
